name: example10
on: [workflow_dispatch]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10,12,14]
        os: [ubuntu-latest, window-latest]
    steps:
      - run: echo  "🎉 The job was automatically triggered by a ${{ github.event_name }} event."