name: example10
on: [workflow_dispatch]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10,12,14]
        os: [ubuntu-latest, window-latest]
    steps:
      - run: echo
name: example09
on: [workflow_dispatch]

jobs:
  Test1:
    concurrency:
      group: demo
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: sleep 10
  Test2:
    concurrency:
      group: demo
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: sleep 5
  Test3:
    concurrency:
      group: demo
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
